name: brewbliss_market
description: BrewBliss Market - coffee-style collectibles marketplace simulation
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.2
  iconly: ^1.0.1
  flutter_3d_controller: any
  flutter_animate: ^4.5.2
  tutorial_coach_mark: ^1.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
